import { MandiPrice } from "./types";

export const FALLBACK_PRICES: MandiPrice[] = [
  {
    state: "Maharashtra",
    district: "Nashik",
    market: "Lasalgaon",
    commodity: "Onion",
    variety: "Onion",
    min_price: "800",
    max_price: "1600",
    modal_price: "1200",
    arrival_date: "30/04/2025",
  },
  {
    state: "Karnataka",
    district: "Kolar",
    market: "Kolar",
    commodity: "Tomato",
    variety: "Tomato",
    min_price: "400",
    max_price: "1200",
    modal_price: "800",
    arrival_date: "30/04/2025",
  },
  {
    state: "Uttar Pradesh",
    district: "Agra",
    market: "Agra",
    commodity: "Potato",
    variety: "Desi",
    min_price: "600",
    max_price: "1000",
    modal_price: "800",
    arrival_date: "30/04/2025",
  },
  {
    state: "Punjab",
    district: "Ludhiana",
    market: "Ludhiana",
    commodity: "Wheat",
    variety: "Lok-1",
    min_price: "2300",
    max_price: "2600",
    modal_price: "2450",
    arrival_date: "30/04/2025",
  },
  {
    state: "Andhra Pradesh",
    district: "Guntur",
    market: "Guntur",
    commodity: "Chilli",
    variety: "Teja",
    min_price: "8000",
    max_price: "14000",
    modal_price: "11000",
    arrival_date: "30/04/2025",
  },
  {
    state: "Madhya Pradesh",
    district: "Indore",
    market: "Indore",
    commodity: "Soybean",
    variety: "Yellow",
    min_price: "4600",
    max_price: "5200",
    modal_price: "4900",
    arrival_date: "30/04/2025",
  },
  {
    state: "Rajasthan",
    district: "Jodhpur",
    market: "Jodhpur",
    commodity: "Garlic",
    variety: "Desi",
    min_price: "2000",
    max_price: "6000",
    modal_price: "4000",
    arrival_date: "30/04/2025",
  },
  {
    state: "Tamil Nadu",
    district: "Erode",
    market: "Erode",
    commodity: "Turmeric",
    variety: "Finger",
    min_price: "9000",
    max_price: "13000",
    modal_price: "11000",
    arrival_date: "30/04/2025",
  },
  {
    state: "Maharashtra",
    district: "Nagpur",
    market: "Nagpur",
    commodity: "Cotton",
    variety: "H-4",
    min_price: "6800",
    max_price: "7400",
    modal_price: "7100",
    arrival_date: "30/04/2025",
  },
  {
    state: "Bihar",
    district: "Patna",
    market: "Patna",
    commodity: "Rice",
    variety: "Coarse",
    min_price: "2200",
    max_price: "3000",
    modal_price: "2600",
    arrival_date: "30/04/2025",
  },
  {
    state: "Karnataka",
    district: "Bellary",
    market: "Bellary",
    commodity: "Maize",
    variety: "Hybrid",
    min_price: "1900",
    max_price: "2400",
    modal_price: "2150",
    arrival_date: "30/04/2025",
  },
];

export const POPULAR_COMMODITIES = [
  "Tomato",
  "Onion",
  "Potato",
  "Wheat",
  "Rice",
  "Maize",
  "Cotton",
  "Soybean",
  "Turmeric",
  "Chilli",
  "Garlic",
];
